baseurl: ''
url: 'https://juli.com.co'
name: Juli Digital
author: Julian Franco
email: contacto@juli.com.co
x: https://x.com/julicomco
title: Páginas web y estrategias digitales para emprendimientos y empresas
disqus-identifier: julidigital

permalink: /:slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

talkyard_server_url: https://site-ibxuu6bz0b.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js