baseurl: ''
url: 'https://juli.com.co'
name: Juli.Com.Co
author: Julian Franco
email: contacto@juli.com.co
linkedin: https://www.linkedin.com/in/seoconjuli/
title: Páginas web y SEO que Venden o Convierten

permalink: /:slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

talkyard_server_url: https://site-ibxuu6bz0b.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js