baseurl: ''
url: 'https://juli.com.co'
name: Juli.Com.Co
linkedin: https://www.linkedin.com/in/tintoconjuli/
instagram: https://www.instagram.com/tintoconjuli/
author:
  name: Julian Franco
  email: contacto@juli.com.co
  linkedin: https://www.linkedin.com/in/tintoconjuli/
  job_title: "SEO y Desarrollador Web"
  bio: "Después de hacer más de 15 páginas web con código, me di cuenta que los clientes estaban felices... pero sin ventas. Así que desde el 2021 hago SEO y copy persuasivo para mis clientes. Ahora están más felices. ¿También vendes poco? Escríbeme"
title: Páginas web y SEO que Venden o Convierten
logo: /img/logo.png 

default_image: /img/juli-desarrollador-web.webp  # Imagen por defecto para posts sin imagen específica
publisher:
  name: Julian Franco
  logo: /img/logo.png
language: es

permalink: /:slug

collections:
  posts:
    output: true
    permalink: /blog/:slug

markdown: kramdown
kramdown:
  parse_block_html: true

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

talkyard_server_url: https://site-ibxuu6bz0b.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js