baseurl: ''
url: 'https://juli.com.co'
name: JULI
author: Julian Franco
email: digitalizaresfacil@gmail.com
title: Páginas web y estrategias digitales para emprendimientos y empresas
yotube: https://www.youtube.com/channel/UCiXWpAvZiAxwv7uzBGBagwQ?view_as=subscriber
tiktok: algo
instagram: https://instagram.com/gurcoff
whatsapp: https://wa.me/573202492786
tel: tel://+573115245225

permalink: /:slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []