baseurl: ''
url: 'https://juli.com.co'
name: Juli Digital
author: Julian Franco
email: digitalizaresfacil@gmail.com
title: Páginas web y estrategias digitales para emprendimientos y empresas
yotube: https://www.youtube.com/channel/UCiXWpAvZiAxwv7uzBGBagwQ
# tiktok: algo
instagram: https://www.instagram.com/julidigitaloficial/
telegram: https://t.me/digitalizaresfacil
tel: tel://+573115245225
disqus-identifier: julidigital

permalink: /:slug

markdown: kramdown

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []